// PRODUCTS
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";
// LOGIN
export const REGISTER = "REGISTER";
export const SIGNIN = "SIGNIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
// OVERLAY
export const IS_LOADING = "IS_LOADING";
export const LOADED = "LOADED";
